### ISSUE TITLE
Sometimes Pl fails when reporting feedback.

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/PlatformInstaller#169]
Related Desk Case:
https://nservicebus.desk.com/agent/case/11282

Customer Reports that when installing products from PI, the following error occurs:

```
Hi, I'm trying to install but get an exception. Rerunning shows all products except ServiceMatrix have installed.

An unhandled exception occurred:
Exception:
Exception has been thrown by the target of an invocation.
StackTrace:
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at Caliburn.Micro.EventAggregator.Handler.Handle(Type messageType, Object message)
at Caliburn.Micro.EventAggregator.<>c__DisplayClass12.<>c__DisplayClass15.<Publish>b__10(Handler handler)
at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at Caliburn.Micro.EventAggregator.<>c__DisplayClass12.<Publish>b__f()
at Caliburn.Micro.XamlPlatformProvider.OnUIThread(Action action)
at Caliburn.Micro.Execute.OnUIThread(Action action)
at Caliburn.Micro.EventAggregator.Publish(Object message, Action`1 marshal)
at Caliburn.Micro.EventAggregatorExtensions.PublishOnUIThread(IEventAggregator eventAggregator, Object message)
at Installer.<Install>d__10.MoveNext()
Source:
mscorlib
TargetSite:
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
Class not registered
StackTrace:
at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
at System.Diagnostics.Process.Start()
at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
at InstallFeedbackReporter.Handle(InstallSucceededEvent message)
Source:
System
TargetSite:
Boolean StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo)
```

**Comment by gbiellem** [comment]
> Class not registered 

Odd, so his machine is a bit broken as it doesn't know how to handle URLs?
Guess we wrap this in a try/catch https://github.com/Particular/PlatformInstaller/blob/master/src/PlatformInstaller/InstallFeedbackReporter.cs#L45 to prevent this from throwing

**Comment by gbiellem** [comment]
Deployed to prod - PI 1.0.0.427
